id = "skript"
name = "Skript"
description = "Skript syntax highlighting for Zed editor"
version = "0.1.0"
schema_version = 1
authors = ["WIL24000223"]
repository = "https://github.com/zephrynis/zed-skript.git"

[grammars.skript]
repository = "https://github.com/zephrynis/zed-skript.git"
commit = "b7aec51281246a8e8cc85336f95f9ffab1f06b4d"
