id = "skript"
name = "Skript"
description = "Skript syntax highlighting for Zed editor"
version = "0.1.0"
schema_version = 1
authors = ["WIL24000223"]
repository = "https://github.com/zephrynis/zed-skript.git"

[grammars.skript]
repository = "https://github.com/zephrynis/zed-skript.git"
commit = "c1672c0f323e732c66a30ebe324fa221c220d3c3"
