id = "skript"
name = "Skript"
description = "Skript syntax highlighting for Zed editor"
version = "0.1.0"
schema_version = 1
authors = ["WIL24000223"]
repository = "https://github.com/zephrynis/zed-skript.git"

[grammars.skript]
repository = "https://github.com/zephrynis/zed-skript.git"
commit = "93226e185b95fe06723315420f461bc35c18f47d"
